https://www.kaggle.com/aakashns/pytorch-basics-linear-regression-from-scratch

#import libraries

In [0]:
import numpy as np
import torch

In [0]:
# Create tensors.
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True) #reguires grad will tell torch that the variable gradients need to be calculated
b = torch.tensor(5., requires_grad=True)

In [42]:
# Arithmetic operations
y = w * x ** x + b
print(y)

tensor(113., grad_fn=<AddBackward0>)




What makes PyTorch special, is that we can automatically compute the derivative of y w.r.t. the tensors that have requires_grad set to True i.e. w and b.


In [0]:
# Compute gradient of variables that had grad = true set previously
y.backward()

In [44]:
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dw: tensor(27.)
dy/db: tensor(1.)


In [0]:
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [0]:
# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [0]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])



Linear Regression Model (from scratch)

The weights and biases can also be represented as matrices, initialized with random values. The first row of w and the first element of b are use to predict the first target variable i.e. yield for apples, and similarly the second for oranges.


In [0]:
# Weights and biases
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)



tensor([[-0.3607, -1.4958, -1.1246],
        [-0.4602,  1.9278,  2.1539]], requires_grad=True)
tensor([-0.1090, -1.7408], requires_grad=True)


In [0]:
# Define the model
def model(x):
    return x @ w.t() + b

In [0]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[-175.0184,  186.4439],
        [-236.5396,  263.8758],
        [-297.1558,  341.4745],
        [-142.8333,  113.9051],
        [-247.3170,  302.3473]], grad_fn=<AddBackward0>)


In [0]:
# MSE loss
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

In [0]:
# Compute loss
loss = mse(preds, targets)
print(loss)

tensor(60035.8516, grad_fn=<DivBackward0>)


In [0]:
# Compute gradients
loss.backward()


In [0]:
# Gradients for weights
print(w)
print(w.grad)

tensor([[-0.3607, -1.4958, -1.1246],
        [-0.4602,  1.9278,  2.1539]], requires_grad=True)
tensor([[-24590.1738, -27980.9688, -17002.8750],
        [ 12390.9346,  14195.7324,   8640.4922]])


In [0]:
# Gradients for bias
print(b)
print(b.grad)

tensor([-0.1090, -1.7408], requires_grad=True)
tensor([-295.9728,  149.6093])


In [0]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)


tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [0]:
# Generate predictions
preds = model(inputs)
print(preds)


tensor([[-175.0184,  186.4439],
        [-236.5396,  263.8758],
        [-297.1558,  341.4745],
        [-142.8333,  113.9051],
        [-247.3170,  302.3473]], grad_fn=<AddBackward0>)


In [0]:
# Calculate the loss
loss = mse(preds, targets)
print(loss)


tensor(60035.8516, grad_fn=<DivBackward0>)


In [0]:
# Compute gradients
loss.backward()


In [0]:
# Adjust weights & reset gradients
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [0]:
print(w)

tensor([[-0.1148, -1.2160, -0.9545],
        [-0.5842,  1.7859,  2.0675]], requires_grad=True)


In [0]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(40855.5391, grad_fn=<DivBackward0>)


In [0]:
# Train for 100 epochs
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [0]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)


tensor(383.3740, grad_fn=<DivBackward0>)


#Using Pytorch built in linear regression model

In [0]:
# Imports
import torch.nn as nn

In [0]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')
# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float32')

In [0]:


inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)



In [0]:
# Import tensor dataset & data loader
from torch.utils.data import TensorDataset, DataLoader

In [0]:
# Define dataset
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]


(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [0]:


# Define data loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)
next(iter(train_dl))



[tensor([[ 91.,  88.,  64.],
         [ 69.,  96.,  70.],
         [ 91.,  88.,  64.],
         [102.,  43.,  37.],
         [ 69.,  96.,  70.]]), tensor([[ 81., 101.],
         [103., 119.],
         [ 81., 101.],
         [ 22.,  37.],
         [103., 119.]])]

#Instead of initializing the weights & biases manually, we can define the model using nn.Linear.

In [0]:


# Define model
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)



Parameter containing:
tensor([[ 0.4469,  0.3284,  0.1947],
        [ 0.2925,  0.2424, -0.4603]], requires_grad=True)
Parameter containing:
tensor([0.5180, 0.4150], requires_grad=True)


In [0]:
# Define optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

Instead of defining a loss function manually, we can use the built-in loss function mse_loss.

In [0]:
# Import nn.functional
import torch.nn.functional as F

In [0]:
# Define loss function
loss_fn = F.mse_loss

In [0]:
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(3480.9136, grad_fn=<MseLossBackward>)


In [0]:
# Define a utility function to train the model
def fit(num_epochs, model, loss_fn, opt):
    for epoch in range(num_epochs):
        for xb,yb in train_dl:
            # Generate predictions
            pred = model(xb)
            loss = loss_fn(pred, yb)
            # Perform gradient descent
            loss.backward()
            opt.step()
            opt.zero_grad()
    print('Training loss: ', loss_fn(model(inputs), targets))

In [0]:
# Train the model for 100 epochs
fit(100, model, loss_fn, opt)

Training loss:  tensor(55.1401, grad_fn=<MseLossBackward>)
